### ISSUE TITLE
Possible to enable emmet for .ftl files?

### ISSUE THREAD

**Issue by jmcdl** [dcortes92/vs-freemarker#20]
Often much of the freemarker code we write is vanilla HTML. Would it be possible to add the ability to use emmet shortcuts within .ftl files?

**Comment by JPeer264** [comment]
This has nothing to do with this extension. You can enable that by adding following into your settings: 

```json
"emmet.includeLanguages": {"ftl": "html"},
```

**Comment by jmcdl** [comment]
Thanks. I definitely should have been able to figure that out!
