### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by dcortes92** [dcortes92/vs-freemarker#8]
There's a problem with the readme shown in the marketplace. Screenshot attached.

<img width="733" alt="readme-issue" src="https://cloud.githubusercontent.com/assets/3781536/22562090/b62a8852-e940-11e6-912e-f8a93b124bda.png">

**Comment by vinlos** [comment]
hello Daniel,

thank you for the merge! I see the issue. I'd try to remove the name of the
language 'freemarker' after the 3 characters ``` and I'd try to replace it
with 'xml' or 'html'. Unfortunately I cannot test the behavior because VsCode
reads the ReadMe markdown directly from your GitHub project.

In any case it's a VSCode issue, since GitHub is able to render it
correctly.

Have a nice day,
Vincenzo

Il giorno gio 2 feb 2017 alle ore 19:11 Daniel Cortes <
notifications@github.com> ha scritto:

**Comment by dcortes92** [comment]
Hi @vinlos, you're right it was a VSCode issue. But I was able to fix it anyway, you can check how I did it in the referenced commit above 🙂 

Thanks,

Daniel

**Comment by vinlos** [comment]
Perfect! Nice workaround!

Il giorno ven 3 feb 2017 alle ore 19:19 Daniel Cortes <
notifications@github.com> ha scritto:
